### ISSUE TITLE
500 error from external service causes memory exception

### ISSUE THREAD

**Issue by nbclark** [doubledutch/StroomData#33]
> java.io.IOException: Server returned HTTP response code: 500 for URL: http://10.208.230.38:8181/api/signals
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at me.doubledutch.stroom.Utility.postURL(Utility.java:43)
	at me.doubledutch.stroom.filters.FilterService.processDocument(FilterService.java:58)
	at me.doubledutch.stroom.filters.FilterService.run(FilterService.java:132)
	at java.lang.Thread.run(Thread.java:745)
java.io.IOException: Server returned HTTP response code: 500 for URL: http://10.208.230.38:8181/api/signals
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at me.doubledutch.stroom.Utility.postURL(Utility.java:43)
	at me.doubledutch.stroom.filters.FilterService.processDocument(FilterService.java:58)
	at me.doubledutch.stroom.filters.FilterService.run(FilterService.java:132)
	at java.lang.Thread.run(Thread.java:745)
java.io.IOException: Server returned HTTP response code: 500 for URL: http://10.208.230.38:8181/api/signals
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at me.doubledutch.stroom.Utility.postURL(Utility.java:43)
	at me.doubledutch.stroom.filters.FilterService.processDocument(FilterService.java:58)
	at me.doubledutch.stroom.filters.FilterService.run(FilterService.java:132)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Service.rules_engine_node" java.lang.OutOfMemoryError: Java heap space
	at me.doubledutch.stroom.streams.Stream.addDocuments(Stream.java:231)
	at me.doubledutch.stroom.streams.Stream.addDocuments(Stream.java:209)
	at me.doubledutch.stroom.LocalStreamConnection.append(LocalStreamConnection.java:88)
	at me.doubledutch.stroom.filters.FilterService.run(FilterService.java:154)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kasperjj** [comment]
Fixed in 0.1.6
