### ISSUE TITLE
Partitioned aggregate kills service if partition key missing

### ISSUE THREAD

**Issue by nbclark** [doubledutch/StroomData#38]
2016-08-02 20:51:47,194 [Aggregate] INFO  cards_manager restarting at 17
org.json.JSONException: JSONObject["UserID"] not found.
	at org.json.JSONObject.get(JSONObject.java:473)
	at me.doubledutch.stroom.Utility.pickValue(Utility.java:29)
	at me.doubledutch.stroom.aggregates.PartitionedAggregateService.getPartitionKey(PartitionedAggregateService.java:137)
	at me.doubledutch.stroom.aggregates.PartitionedAggregateService.run(PartitionedAggregateService.java:242)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kasperjj** [comment]
Fixed, will be included in v0.1.7
